name: KBOT-CICD

on: 
    push:
      branches:
        - develop
env:
    TARGETOS: linux
    TARGETARCH: amd64

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Run test
              run: make test
            - name: GHCR login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}
            - name: Docker Hub login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build&Push
              env:
                APP: "kbot"
                REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
              run: make image push
    cd:
        name: CD
        needs: ci
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: echo "VERSION=$(git describe --tags --abbrev=0 --always)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - uses: mikefarah/yq@master
              with:
                cmd: yq -i '.image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

            - run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git commit -am "update version $VERSION"
                git push